import type { BookInput } from "../../src/shared/types";
import { clearAllBooks, createBook } from "./libraryRepository";

type DemoBook = BookInput;

const cover = (isbn: string) => `https://covers.openlibrary.org/b/isbn/${isbn}-L.jpg`;

const DEMO_BOOKS: DemoBook[] = [
  {
    displayTitle: "Crime and Punishment",
    workTitle: "Crime and Punishment",
    author: "Fyodor Dostoevsky",
    year: 2002,
    firstPublishedYear: 1866,
    category: "Fiction",
    genres: ["Fiction", "Psychological fiction"],
    subjects: ["Fiction"],
    publisher: "Penguin Classics",
    pageCount: 671,
    language: "en",
    status: "reading",
    rating: 5,
    readDate: null,
    coverUrl: cover("9780143058144"),
    coverSource: "isbn",
    coverStatus: "remote",
    isbn: "9780143058144",
    description: "A poor ex-student plots a murder in St. Petersburg and wrestles with guilt, faith, and redemption.",
    source: "demo",
    metadataQuality: 92
  },
  {
    displayTitle: "The Idiot",
    workTitle: "The Idiot",
    author: "Fyodor Dostoevsky",
    year: 2003,
    firstPublishedYear: 1869,
    category: "Fiction",
    genres: ["Fiction", "Classics"],
    subjects: ["Fiction"],
    publisher: "Vintage",
    pageCount: 732,
    language: "en",
    status: "reading",
    rating: null,
    readDate: null,
    coverUrl: cover("9780374528379"),
    coverSource: "isbn",
    coverStatus: "remote",
    isbn: "9780374528379",
    description: "Prince Myshkin returns to Russia and unsettles society with his innocence and honesty.",
    source: "demo",
    metadataQuality: 90
  },
  {
    displayTitle: "The Gambler",
    workTitle: "The Gambler",
    author: "Fyodor Dostoevsky",
    year: 2005,
    firstPublishedYear: 1867,
    category: "Fiction",
    genres: ["Fiction", "Classics"],
    subjects: ["Fiction"],
    publisher: "Dover Publications",
    pageCount: 160,
    language: "en",
    status: "reading",
    rating: null,
    readDate: null,
    coverUrl: cover("9780486282372"),
    coverSource: "isbn",
    coverStatus: "remote",
    isbn: "9780486282372",
    description: "Obsession with roulette consumes a tutor in a German spa town.",
    source: "demo",
    metadataQuality: 88
  },
  {
    displayTitle: "The Will to Power",
    workTitle: "The Will to Power",
    author: "Friedrich Nietzsche",
    year: 2017,
    firstPublishedYear: 1901,
    category: "Philosophy",
    genres: ["Philosophy"],
    subjects: ["Philosophy"],
    publisher: "Penguin Classics",
    pageCount: 448,
    language: "en",
    status: "want",
    rating: 5,
    readDate: null,
    coverUrl: cover("9780140446173"),
    coverSource: "isbn",
    coverStatus: "remote",
    isbn: "9780140446173",
    description: "Selections from Nietzsche's notebooks on morality, art, and the revaluation of values.",
    source: "demo",
    metadataQuality: 86
  },
  {
    displayTitle: "The Prince",
    workTitle: "The Prince",
    author: "Niccolò Machiavelli",
    year: 2003,
    firstPublishedYear: 1532,
    category: "Philosophy",
    genres: ["Philosophy", "Political science"],
    subjects: ["Political science"],
    publisher: "Penguin Classics",
    pageCount: 176,
    language: "en",
    status: "want",
    rating: null,
    readDate: null,
    coverUrl: cover("9780140449150"),
    coverSource: "isbn",
    coverStatus: "remote",
    isbn: "9780140449150",
    description: "A Renaissance treatise on power, leadership, and statecraft.",
    source: "demo",
    metadataQuality: 90
  },
  {
    displayTitle: "1984",
    workTitle: "Nineteen Eighty-Four",
    author: "George Orwell",
    year: 2021,
    firstPublishedYear: 1949,
    category: "Fiction",
    genres: ["Fiction", "Dystopian"],
    subjects: ["Fiction"],
    publisher: "Signet",
    pageCount: 328,
    language: "en",
    status: "want",
    rating: 5,
    readDate: null,
    coverUrl: cover("9780451524935"),
    coverSource: "isbn",
    coverStatus: "remote",
    isbn: "9780451524935",
    description: "In a totalitarian state, Winston Smith rebels against surveillance and thought control.",
    source: "demo",
    metadataQuality: 94
  },
  {
    displayTitle: "The Metamorphosis",
    workTitle: "The Metamorphosis",
    author: "Franz Kafka",
    year: 1996,
    firstPublishedYear: 1915,
    category: "Fiction",
    genres: ["Fiction", "Absurdist fiction"],
    subjects: ["Fiction"],
    publisher: "Schocken",
    pageCount: 201,
    language: "en",
    status: "want",
    rating: null,
    readDate: null,
    coverUrl: cover("9780805210576"),
    coverSource: "isbn",
    coverStatus: "remote",
    isbn: "9780805210576",
    description: "Gregor Samsa wakes transformed and watches his family adjust to the change.",
    source: "demo",
    metadataQuality: 88
  },
  {
    displayTitle: "A Clockwork Orange",
    workTitle: "A Clockwork Orange",
    author: "Anthony Burgess",
    year: 1995,
    firstPublishedYear: 1962,
    category: "Fiction",
    genres: ["Fiction", "Dystopian"],
    subjects: ["Fiction"],
    publisher: "W. W. Norton",
    pageCount: 213,
    language: "en",
    status: "want",
    rating: null,
    readDate: null,
    coverUrl: cover("9780393312836"),
    coverSource: "isbn",
    coverStatus: "remote",
    isbn: "9780393312836",
    description: "Alex and his gang roam a violent future England until the state tries to reform him.",
    source: "demo",
    metadataQuality: 90
  },
  {
    displayTitle: "Critique of Pure Reason",
    workTitle: "Critique of Pure Reason",
    author: "Immanuel Kant",
    year: 2007,
    firstPublishedYear: 1781,
    category: "Philosophy",
    genres: ["Philosophy"],
    subjects: ["Philosophy"],
    publisher: "Penguin Classics",
    pageCount: 784,
    language: "en",
    status: "want",
    rating: null,
    readDate: null,
    coverUrl: cover("9780140447477"),
    coverSource: "isbn",
    coverStatus: "remote",
    isbn: "9780140447477",
    description: "Kant examines the limits of human knowledge and the foundations of metaphysics.",
    source: "demo",
    metadataQuality: 84
  },
  {
    displayTitle: "Eugene Onegin",
    workTitle: "Eugene Onegin",
    author: "Alexander Pushkin",
    year: 2009,
    firstPublishedYear: 1833,
    category: "Poetry",
    genres: ["Poetry", "Classics"],
    subjects: ["Poetry"],
    publisher: "Oxford University Press",
    pageCount: 240,
    language: "en",
    status: "want",
    rating: null,
    readDate: null,
    coverUrl: cover("9780199538646"),
    coverSource: "isbn",
    coverStatus: "remote",
    isbn: "9780199538646",
    description: "Pushkin's novel in verse follows a jaded aristocrat and the people around him.",
    source: "demo",
    metadataQuality: 86
  },
  {
    displayTitle: "Blood Meridian",
    workTitle: "Blood Meridian",
    author: "Cormac McCarthy",
    year: 2010,
    firstPublishedYear: 1985,
    category: "Fiction",
    genres: ["Fiction", "Western"],
    subjects: ["Fiction"],
    publisher: "Vintage",
    pageCount: 351,
    language: "en",
    status: "read",
    rating: 5,
    readDate: "2025-11-02",
    coverUrl: cover("9780679728759"),
    coverSource: "isbn",
    coverStatus: "remote",
    isbn: "9780679728759",
    description: "A teenage runaway joins a scalp-hunting party on the Texas–Mexico border.",
    source: "demo",
    metadataQuality: 92
  },
  {
    displayTitle: "Brave New World",
    workTitle: "Brave New World",
    author: "Aldous Huxley",
    year: 2006,
    firstPublishedYear: 1932,
    category: "Fiction",
    genres: ["Fiction", "Dystopian"],
    subjects: ["Fiction"],
    publisher: "Harper Perennial",
    pageCount: 288,
    language: "en",
    status: "paused",
    rating: 4,
    readDate: null,
    coverUrl: cover("9780060850524"),
    coverSource: "isbn",
    coverStatus: "remote",
    isbn: "9780060850524",
    description: "A engineered society of comfort confronts an outsider from the Savage Reservation.",
    source: "demo",
    metadataQuality: 90
  }
];

export function seedDemoLibrary(replace = true) {
  if (replace) clearAllBooks();
  return DEMO_BOOKS.map((book) => createBook(book));
}

export function getDemoBookCount() {
  return DEMO_BOOKS.length;
}
